DROP TABLE IF EXISTS attachments CASCADE;
DROP TABLE IF EXISTS task_tags CASCADE;
DROP TABLE IF EXISTS comments CASCADE;
DROP TABLE IF EXISTS tasks CASCADE;
DROP TABLE IF EXISTS tags CASCADE;
DROP TABLE IF EXISTS project_members CASCADE;
DROP TABLE IF EXISTS projects CASCADE;
DROP TABLE IF EXISTS clients CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE users (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL,
    profile_picture VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE clients (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    contact_email VARCHAR(255) NOT NULL,
    contact_phone VARCHAR(20) NOT NULL,
    industry VARCHAR(50) NOT NULL,
    logo VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE projects (
    ID SERIAL PRIMARY KEY,
    client_ID INT,
    owner_ID INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    start_date DATE NOT NULL,
    end_date DATE,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    type VARCHAR(50) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (client_ID) REFERENCES clients(ID) ON DELETE SET NULL,
    FOREIGN KEY (owner_ID) REFERENCES users(ID)
);

CREATE TABLE project_members (
    project_ID INT NOT NULL,
    user_ID INT NOT NULL,
    role VARCHAR(50) NOT NULL,
    joined_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (project_ID) REFERENCES projects(ID) ON DELETE CASCADE,
    FOREIGN KEY (user_ID) REFERENCES users(ID) ON DELETE CASCADE,
    PRIMARY KEY (project_ID, user_ID)
);

CREATE TABLE tasks (
    ID SERIAL PRIMARY KEY,
    project_ID INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    due_date DATE NOT NULL,
    status VARCHAR(50) NOT NULL,
    priority VARCHAR(50) NOT NULL,
    assigned_to INT,
    created_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,
    FOREIGN KEY (project_ID) REFERENCES projects(ID) ON DELETE CASCADE,
    FOREIGN KEY (assigned_to) REFERENCES users(ID) ON DELETE SET NULL,
    FOREIGN KEY (created_by) REFERENCES users(ID) ON DELETE SET NULL
);

CREATE TABLE tags (
    ID SERIAL PRIMARY KEY,
    name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE task_tags (
    task_ID INT NOT NULL,
    tag_ID INT NOT NULL,
    FOREIGN KEY (task_ID) REFERENCES tasks(ID) ON DELETE CASCADE,
    FOREIGN KEY (tag_ID) REFERENCES tags(ID) ON DELETE CASCADE,
    PRIMARY KEY (task_ID, tag_ID)
);

CREATE TABLE comments (
    ID SERIAL PRIMARY KEY,
    task_ID INT NOT NULL,
    user_ID INT,
    content TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_ID) REFERENCES tasks(ID) ON DELETE CASCADE,
    FOREIGN KEY (user_ID) REFERENCES users(ID) ON DELETE SET NULL
);

CREATE TABLE attachments (
    ID SERIAL PRIMARY KEY,
    file_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(255) NOT NULL,
    task_ID INT NOT NULL,
    uploaded_by INT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (task_ID) REFERENCES tasks(ID) ON DELETE CASCADE,
    FOREIGN KEY (uploaded_by) REFERENCES users(ID) ON DELETE SET NULL
);